version: '2'

services:
  node:
    build: .
    image: herrphon/node
    container_name: node
    environment:
    - NODE_ENV=development
    mem_limit: 128m
    memswap_limit: 1g
    ports:
      - "3000:3000"
    volumes:
      - "./app:/app"
